### ISSUE TITLE
validate_object should only validate, not change the error string

### ISSUE THREAD

**Issue by kdaily** [cw-dvr8/JSON-validation-schemas#5]
Have another utility to modify error text to put in context of the whole file, not part of the `validate_object` function

**Comment by cw-dvr8** [comment]
Since the validate_object function only had one line that did the actual validation and the rest of it was error_handling, I elected to pull the line that ran the jsonschema validator out of the function and put it in the main validation module.  I renamed the function to validation_errors, and now it is exclusively used to format error messages and takes the deque output from the validator as an argument, along with any text that should be prepended to the error message.
